export const articles = [
    {
        id: 1,
        title: "Understanding Anxiety in the Modern World",
        author: "Dr. Sarah Johnson",
        image: "https://picsum.photos/400/250?random=1",
        year: 2024,
        category: "Mental Health",
        readTime: "8 min read",
        description: "Explore the roots of modern anxiety and discover evidence-based strategies for managing overwhelming feelings.",
    },
    {
        id: 2,
        title: "The Science of Mindfulness Meditation",
        author: "Prof. Michael Chen",
        image: "https://picsum.photos/400/250?random=2",
        year: 2024,
        category: "Meditation",
        readTime: "12 min read",
        description: "Dive deep into the neuroscience behind mindfulness and how it rewires your brain for better mental health.",
    },
    {
        id: 3,
        title: "Building Resilience Through Daily Practices",
        author: "Dr. Emily Rodriguez",
        image: "https://picsum.photos/400/250?random=3",
        year: 2024,
        category: "Self-Care",
        readTime: "6 min read",
        description: "Learn practical techniques to strengthen your psychological resilience and bounce back from life's challenges.",
    },
    {
        id: 4,
        title: "Digital Detox for Mental Clarity",
        author: "Dr. James Wilson",
        image: "https://picsum.photos/400/250?random=4",
        year: 2024,
        category: "Wellness",
        readTime: "10 min read",
        description: "Understand how constant connectivity affects your mind and discover strategies for healthy digital boundaries.",
    },
    {
        id: 5,
        title: "The Psychology of Habit Formation",
        author: "Dr. Lisa Thompson",
        image: "https://picsum.photos/400/250?random=5",
        year: 2024,
        category: "Behavioral Psychology",
        readTime: "9 min read",
        description: "Uncover the science behind how habits form and learn to create positive behavioral changes that stick.",
    },
    {
        id: 6,
        title: "Managing Stress in High-Pressure Environments",
        author: "Dr. Robert Kim",
        image: "https://picsum.photos/400/250?random=6",
        year: 2024,
        category: "Stress Management",
        readTime: "11 min read",
        description: "Practical strategies for maintaining mental health while navigating demanding work and personal situations.",
    },
    {
        id: 7,
        title: "The Art of Self-Compassion",
        author: "Dr. Maria Santos",
        image: "https://picsum.photos/400/250?random=7",
        year: 2024,
        category: "Self-Care",
        readTime: "7 min read",
        description: "Learn to treat yourself with kindness and understanding, especially during difficult times.",
    },
    {
        id: 8,
        title: "Sleep Psychology: Optimizing Rest for Mental Health",
        author: "Dr. David Lee",
        image: "https://picsum.photos/400/250?random=8",
        year: 2024,
        category: "Sleep Health",
        readTime: "13 min read",
        description: "Understand the crucial connection between quality sleep and psychological well-being.",
    },
    {
        id: 9,
        title: "Cognitive Behavioral Techniques for Daily Life",
        author: "Dr. Jennifer Brown",
        image: "https://picsum.photos/400/250?random=9",
        year: 2024,
        category: "CBT",
        readTime: "15 min read",
        description: "Apply proven cognitive-behavioral strategies to reshape negative thought patterns and improve mood.",
    },
    {
        id: 10,
        title: "The Neuroscience of Emotional Regulation",
        author: "Dr. Andrew Davis",
        image: "https://picsum.photos/400/250?random=10",
        year: 2024,
        category: "Neuroscience",
        readTime: "14 min read",
        description: "Explore how your brain processes emotions and learn techniques to better regulate emotional responses.",
    },
    {
        id: 11,
        title: "Mindful Eating and Mental Health",
        author: "Dr. Rachel Green",
        image: "https://picsum.photos/400/250?random=11",
        year: 2024,
        category: "Nutrition Psychology",
        readTime: "8 min read",
        description: "Discover the connection between mindful eating practices and improved psychological well-being.",
    },
    {
        id: 12,
        title: "Breaking the Cycle of Negative Thinking",
        author: "Dr. Thomas Miller",
        image: "https://picsum.photos/400/250?random=12",
        year: 2024,
        category: "Cognitive Health",
        readTime: "10 min read",
        description: "Identify and interrupt destructive thought patterns with evidence-based psychological techniques.",
    },
    {
        id: 13,
        title: "The Power of Gratitude in Mental Health",
        author: "Dr. Susan Taylor",
        image: "https://picsum.photos/400/250?random=13",
        year: 2024,
        category: "Positive Psychology",
        readTime: "6 min read",
        description: "Explore how gratitude practices can significantly impact your mood, relationships, and overall well-being.",
    },
    {
        id: 14,
        title: "Dealing with Perfectionism and Self-Criticism",
        author: "Dr. Mark Anderson",
        image: "https://picsum.photos/400/250?random=14",
        year: 2024,
        category: "Self-Acceptance",
        readTime: "12 min read",
        description: "Learn to recognize perfectionist tendencies and develop healthier standards for yourself.",
    },
    {
        id: 15,
        title: "The Psychology of Creativity and Flow States",
        author: "Dr. Amanda White",
        image: "https://picsum.photos/400/250?random=15",
        year: 2024,
        category: "Peak Performance",
        readTime: "11 min read",
        description: "Understand the mental conditions that foster creativity and how to achieve flow states more consistently.",
    },
    {
        id: 16,
        title: "Social Media and Mental Health: Finding Balance",
        author: "Dr. Kevin Johnson",
        image: "https://picsum.photos/400/250?random=16",
        year: 2024,
        category: "Digital Wellness",
        readTime: "9 min read",
        description: "Navigate the psychological impacts of social media and develop healthier online habits.",
    },
    {
        id: 17,
        title: "Breathwork for Anxiety and Stress Relief",
        author: "Dr. Nicole Parker",
        image: "https://picsum.photos/400/250?random=17",
        year: 2024,
        category: "Breathing Techniques",
        readTime: "7 min read",
        description: "Master simple yet powerful breathing exercises that can instantly calm your nervous system.",
    },
    {
        id: 18,
        title: "Understanding and Processing Grief",
        author: "Dr. Patricia Moore",
        image: "https://picsum.photos/400/250?random=18",
        year: 2024,
        category: "Grief Counseling",
        readTime: "16 min read",
        description: "Navigate the complex emotions of loss with compassionate guidance and practical coping strategies.",
    },
    {
        id: 19,
        title: "The Psychology of Motivation and Goal Setting",
        author: "Dr. Christopher Lee",
        image: "https://picsum.photos/400/250?random=19",
        year: 2024,
        category: "Motivation",
        readTime: "10 min read",
        description: "Understand what truly drives human behavior and learn to set goals that align with intrinsic motivation.",
    },
    {
        id: 20,
        title: "Trauma-Informed Self-Care Practices",
        author: "Dr. Laura Martinez",
        image: "https://picsum.photos/400/250?random=20",
        year: 2024,
        category: "Trauma Recovery",
        readTime: "13 min read",
        description: "Learn gentle, trauma-informed approaches to self-care that honor your healing journey.",
    },
    {
        id: 21,
        title: "The Science of Happiness: What Really Works",
        author: "Dr. Brian Wilson",
        image: "https://picsum.photos/400/250?random=21",
        year: 2024,
        category: "Positive Psychology",
        readTime: "12 min read",
        description: "Explore research-backed strategies for increasing life satisfaction and psychological well-being.",
    },
    {
        id: 22,
        title: "Mindful Parenting: Raising Emotionally Healthy Children",
        author: "Dr. Stephanie Garcia",
        image: "https://picsum.photos/400/250?random=22",
        year: 2024,
        category: "Family Psychology",
        readTime: "14 min read",
        description: "Apply mindfulness principles to parenting and help children develop emotional intelligence.",
    },
    {
        id: 23,
        title: "The Psychology of Procrastination and How to Overcome It",
        author: "Dr. Daniel Clark",
        image: "https://picsum.photos/400/250?random=23",
        year: 2024,
        category: "Productivity",
        readTime: "9 min read",
        description: "Understand the psychological roots of procrastination and develop strategies to increase motivation.",
    },
    {
        id: 24,
        title: "Building Healthy Boundaries in Relationships",
        author: "Dr. Michelle Adams",
        image: "https://picsum.photos/400/250?random=24",
        year: 2024,
        category: "Relationship Health",
        readTime: "11 min read",
        description: "Learn to set and maintain boundaries that protect your mental health and improve relationships.",
    },
    {
        id: 25,
        title: "The Mind-Body Connection in Healing",
        author: "Dr. Richard Turner",
        image: "https://picsum.photos/400/250?random=25",
        year: 2024,
        category: "Holistic Health",
        readTime: "15 min read",
        description: "Explore how mental and physical health are interconnected and support overall well-being.",
    },
    {
        id: 26,
        title: "Seasonal Affective Patterns and Light Therapy",
        author: "Dr. Catherine Lewis",
        image: "https://picsum.photos/400/250?random=26",
        year: 2024,
        category: "Seasonal Wellness",
        readTime: "8 min read",
        description: "Understand how seasons affect mood and discover natural ways to maintain mental health year-round.",
    },
    {
        id: 27,
        title: "The Psychology of Change: Embracing Life Transitions",
        author: "Dr. Gregory Hall",
        image: "https://picsum.photos/400/250?random=27",
        year: 2024,
        category: "Life Transitions",
        readTime: "10 min read",
        description: "Navigate major life changes with psychological insights and practical adaptation strategies.",
    }
]

export const meditations = [
    {
        id: 1,
        title: "Morning Mindfulness",
        instructor: "Sarah Chen",
        duration: "10 min",
        category: "Mindfulness",
        level: "Beginner",
        description: "Start your day with clarity and intention through this gentle mindfulness practice."
    },
    {
        id: 2,
        title: "Anxiety Relief Breathing",
        instructor: "Dr. Michael Torres",
        duration: "15 min",
        category: "Anxiety",
        level: "All Levels",
        description: "Calming breath work specifically designed to reduce anxiety and promote relaxation."
    },
    {
        id: 3,
        title: "Sleep Preparation",
        instructor: "Lisa Harmony",
        duration: "20 min",
        category: "Sleep",
        level: "Beginner",
        description: "Prepare your mind and body for restful sleep with this soothing guided meditation."
    },
    {
        id: 4,
        title: "Stress Release Scan",
        instructor: "Dr. James Rivers",
        duration: "25 min",
        category: "Stress Relief",
        level: "Intermediate",
        description: "Progressive body scan meditation to release tension and accumulated stress."
    },
    {
        id: 5,
        title: "Self-Compassion Practice",
        instructor: "Maria Wellness",
        duration: "18 min",
        category: "Self-Care",
        level: "All Levels",
        description: "Cultivate kindness toward yourself with this heart-centered meditation practice."
    }
]